### PR TITLE
Move to vsc-install testing & fix license

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by JensTimmerman** [comment]
I changed the tests to use `setup.py test` so jenkins, test this please.

**Comment by JensTimmerman** [comment]
depends on https://github.com/hpcugent/vsc-install/pull/6

**Comment by JensTimmerman** [comment]
dependency was merged, jenkins, test this please

**Comment by JensTimmerman** [comment]
still fails due to https://github.com/hpcugent/vsc-install/issues/8

**Comment by JensTimmerman** [comment]
jenkins test this please

**Comment by JensTimmerman** [comment]
bump vsc-install dep

**Comment by stdweird** [comment]
done via vsc-base bump

**Comment by JensTimmerman** [comment]
the version you bumped to is not available on pipy yet.

**Comment by stdweird** [comment]
@JensTimmerman  https://github.com/hpcugent/vsc-base/pull/212

**Comment by JensTimmerman** [comment]
jenkins test this please

**Comment by boegel** [comment]
vsc-base 2.4.14 is now on PyPI

Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
hmm, my attempts to make Jenkins report the test results here with a comment fail... maybe @JensTimmerman can take a look?

**Comment by JensTimmerman** [comment]
@boegel I don't see what's wrong, it's tested.

**Comment by boegel** [comment]
@JensTimmerman: our bot isn't adding comments that indicate whether tests have failed or succeeded, I find it very useful when it does

**Pull request merged**
