### PR TITLE
Handle corrupt pickle failure

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by JensTimmerman** [comment]
Can you add a test so this part of the code is covered in future tests?

**Comment by stdweird** [comment]
@JensTimmerman not easily, unless pylint or something else can do static checks to spot bugs like this

**Comment by JensTimmerman** [comment]
well, see https://github.com/hpcugent/vsc-utils/pull/22 for a test that covers this peace of code.
(tip, you can see https://jenkins1.ugent.be/job/vsc-utils-python26/Coverage/ to know what code is tested or not)

**Comment by boegel** [comment]
s/peace/piece/ ;)

**Pull request merged**
