### PR TITLE
remove sys.exc_clear, it does not exist in python3

### PR DESCRIPTION
**Pull request by wdpypere**

### CODE REVIEW

**Comment by wdpypere** [comment]
it will probable need the fixes in https://github.com/hpcugent/vsc-utils/pull/77 first

**Comment by wdpypere** [comment]
it makes no sense for python2 either. as the next statement calls self.critical, which calls simple_nagios.critical, which sys.exit.

**Comment by stdweird** [comment]
@wdpypere we should try this on a check that raises an exception. this does more than you think (in particular, `sys.exit` might not play nice)

**Comment by stdweird** [comment]
removing it looks ok. this is the output of a forced exception (first thing in the `do` method): 1st with the sys.exc_clear, second without
```
2021-04-15T08:38:25+0000
2021-04-15 10:38:25,954 INFO       TimestampedPidLockfile MainThread  Obtained lock on timestamped pid lockfile /var/lock/xdmod_reporting.lock
2021-04-15 10:38:25,954 INFO       XDMOD_REPORTING MainThread  xdmod_reporting has started
2021-04-15 10:38:25,955 INFO       root            MainThread  xdmod_reporting started.
2021-04-15 10:38:25,959 INFO       root            MainThread  Using timestamp 1618455594
2021-04-15 10:38:25,960 INFO       root            MainThread  Using start timestamp 1618455594
2021-04-15 10:38:25,960 INFO       root            MainThread  Using current time 2021-04-15 08:38:18.960105+00:00
2021-04-15 10:38:25,961 ERROR      root            MainThread  Script failed in a horrible way: this is a test
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vsc/utils/script_tools.py", line 401, in main
    errors = self.do(self.options.dry_run)
  File "/usr/lib/python2.7/site-packages/vsc/reporting/xdmod/consumer.py", line 121, in do
    raise Exception("this is a test")
Exception: this is a test
CRITICAL Script failed in a horrible way
2021-04-15T08:39:16+0000
2021-04-15 10:39:17,222 WARNING    TimestampedPidLockfile MainThread  Obsolete lockfile detected at /var/lock/xdmod_reporting.lock: pid = 16719, timestamp = Thu Apr 15 10:38:25 2021
2021-04-15 10:39:17,222 INFO       XDMOD_REPORTING MainThread  xdmod_reporting has started
2021-04-15 10:39:17,222 INFO       root            MainThread  xdmod_reporting started.
2021-04-15 10:39:17,227 INFO       root            MainThread  Using timestamp 1618455594
2021-04-15 10:39:17,228 INFO       root            MainThread  Using start timestamp 1618455594
2021-04-15 10:39:17,228 INFO       root            MainThread  Using current time 2021-04-15 08:39:10.228077+00:00
2021-04-15 10:39:17,229 ERROR      root            MainThread  Script failed in a horrible way: this is a test
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vsc/utils/script_tools.py", line 401, in main
    errors = self.do(self.options.dry_run)
  File "/usr/lib/python2.7/site-packages/vsc/reporting/xdmod/consumer.py", line 121, in do
    raise Exception("this is a test")
Exception: this is a test
CRITICAL Script failed in a horrible way
```

**Pull request merged**
